Show notification on kill
BasedHardware/Friend pull request #333
Opened 2024-06-21 23:32 UTC by Becca-Saka

Fixes #318

2024-06-22 08:21 UTC, josancamon19 commented
Awesome, as per the approach I see, you built the code for android and iOS right, and are calling it through flutter.
Weren't there any libraries available?

Also, could you please use linting rule of line character length of 120 + default `dart format` / android studio default rules.

2024-06-22 13:58 UTC, Becca-Saka commented
There are libraries but they haven't been updated in a while. 

I will fix this lint issue and tag you again.

> Awesome, as per the approach I see, you built the code for android and iOS right, and are calling it through flutter. Weren't there any libraries available?
> 
> Also, could you please use linting rule of line character length of 120 + default `dart format` / android studio default rules.

2024-06-22 15:28 UTC, Becca-Saka commented
@josancamon19 fixed the lint issue.

2024-06-22 19:16 UTC, josancamon19 approved these changes

2024-06-22 19:39 UTC, josancamon19 requested changes

2024-06-22 19:39 UTC, josancamon19 commented on apps/AppWithWearable/ios/Runner/AppDelegate.swift
> +    UNUserNotificationCenter.current().requestAuthorization(options: [.alert, .sound, .badge]) { granted, error in
Same here, let's not request notifications right when it opens.

2024-06-22 19:39 UTC, josancamon19 commented on apps/AppWithWearable/android/app/src/main/AndroidManifest.xml
>      <uses-permission android:name="android.permission.FOREGROUND_SERVICE" />
Doesn't seem to be reliable on android.
And let's not ask for permissions right when the app opens.

https://github.com/BasedHardware/Friend/assets/18078879/c1edc2cc-3257-4250-9897-5187959df398

2024-06-22 19:42 UTC, josancamon19 commented
Also let's set the notification content to:
title: Friend Device Disconnected
body: Please keep your app opened to continue using your Friend.

2024-06-23 20:10 UTC, Becca-Saka commented
> Also let's set the notification content to: title: Friend Device Disconnected body: Please keep your app opened to continue using your Friend.

Got it, I will work on the requested changes tomorrow.

2024-06-24 18:15 UTC, josancamon19 commented
Hi @Becca-Saka are there any updates to this?

2024-06-24 18:17 UTC, josancamon19 commented
I will go ahead and merge this as it is, because it is useful. But looking forward for the remaining changes, thanks!

2024-06-24 18:18 UTC, merged

2024-06-25 13:12 UTC, Becca-Saka commented
Hi @josancamon19  Sorry for the delayed response. I removed the notification request on the start-up

I created a new PR here https://github.com/BasedHardware/Friend/pull/355

I couldn't replicate the Android issues, you raised though.



https://github.com/BasedHardware/Friend/assets/47469638/03820210-f9ed-4f2a-89a8-152e59ab39de

2024-06-25 13:12 UTC, Becca-Saka commented
We should probably move our conversation to the new PR?