feat: notification action routing
BasedHardware/Friend pull request #373
Opened 2024-06-27 03:53 UTC by SHAH-JI

Description:

- You can send the path in the notification payload and when user receive the notification, the app will navigate according to path
Example:
```dart
createNotification(title: 'Test Notification', body: 'This is a test notification', payload: {'path': '/chat'});
```
- For more screens in the future, you  can update the `screensWithRespectToPath` variable in `notification.dart` file

Changes:

- Added Navigator key for navigation in the MyApp in main.dart
- Added a setter and getter for the screen position in SharedPreferencesUtil

2024-06-27 03:54 UTC, SHAH-JI commented
to @josancamon19 Please check the PR and if there any changes requested let me know.
Thanks.

2024-06-27 08:36 UTC, josancamon19 requested changes
Please use 120 chars line length for linting.

2024-06-27 15:17 UTC, mshahjahan-mufin commented
to @josancamon19 Please confirm, I have set it to 120 chars line length.

2024-06-29 00:17 UTC, josancamon19 commented
Taking a look at it rn

2024-06-29 00:21 UTC, josancamon19 commented
Hi @mshahjahan-mufin, weird, I still see linting issues:

Use android studio linting with the rule change of 120 chars.
Or you can use `dart format`
![CleanShot 2024-06-28 at 17 20 43@2x](https://github.com/BasedHardware/Friend/assets/18078879/4e9a80f6-2c19-4e69-92fe-c4b8bab61dc7)

2024-06-29 00:30 UTC, josancamon19 commented
This implementation looks great, what could we do if we want to access, a specific memory or settings or plugins from the notification? Let's implement this @mshahjahan-mufin

2024-06-29 00:31 UTC, josancamon19 commented
We can do some other parameter in payload like navigateTo, and handle that on home/page.dart

2024-06-29 00:36 UTC, josancamon19 requested changes

2024-06-29 00:36 UTC, josancamon19 commented on apps/AppWithWearable/lib/pages/home/page.dart
>      SharedPreferencesUtil().onboardingCompleted = true;
Also, please include payload /chat to this notification:

```
    createNotification(
      title: 'Here is your action plan for tomorrow',
      body: 'Check out your daily summary to see what you should do tomorrow.',
      notificationId: 5,
      isDailySummaryNotification: true,
      payload: {'path': '/chat'},
    );
```

2024-06-29 04:25 UTC, SHAH-JI commented
to @josancamon19 
Changes done.
1. Character line set 120 and formatted.
2. Subpage routing completed, you can send the subpage route into `payload['navigateTo']` and add the screen in the `screensWithRespectToPath` JSON object in `home/page.dart` file.

2024-06-30 01:30 UTC, josancamon19 approved these changes

2024-06-30 01:30 UTC, merged

2024-06-30 01:31 UTC, josancamon19 commented
@SHAH-JI Great job, thanks! 🎉

Please send me your transfer details to joan.santiago.cabezas@gmail.com